# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "ansible_local" do |ansible|
    ansible.inventory_path = "/vagrant/ansible/hosts.ini"
      ansible.galaxy_role_file = "/vagrant/ansible/requirements.yml"
      ansible.galaxy_roles_path = "/vagrant/ansible/roles"
    ansible.playbook = "ansible/vagrant.yml"
    ansible.verbose = "vv"
   end

  # Prefer VirtualBox before VMware Fusion
  config.vm.provider "virtualbox"
  config.vm.provider "vmware_fusion"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.gui = false
    virtualbox.customize ["modifyvm", :id, "--memory", 2048]
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  # disable guest additions
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root"

  config.vm.define :centos6, autostart: true do |centos6_config|
    centos6_config.vm.box = "redesign/centos6"
    centos6_config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2201, auto_correct: true

    centos6_config.vm.provider "virtualbox" do |vb|
      vb.name = "redesign"
    end
  end
end
