---
# This playbook is run from vagrant for testing the box
- hosts: centos7
  user: vagrant
  become: yes

  pre_tasks:
    - name: show distribution
      debug: msg={{ ansible_distribution }}

  roles:
    []
