---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: centos6
    box: redesign/centos6
    box_url: https://app.vagrantup.com/redesign/boxes/centos6
    memory: 1024
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - auto_config: true
        ip: 192.168.22.6
        network_name: private_network
        type: static
  - name: centos7
    box: redesign/centos7
    box_url: https://app.vagrantup.com/redesign/boxes/centos7
    memory: 1024
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - auto_config: true
        ip: 192.168.22.7
        network_name: private_network
        type: static
provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
